name: Build Android
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # FIX: Instalar Java 17 (Requerido por Android moderno)
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Versión estable recomendada

      - run: flutter pub get

      # FIX CRÍTICO: Arreglar saltos de línea de Windows y dar permisos
      - run: |
          sed -i 's/\r$//' android/gradlew
          chmod +x android/gradlew
      
      - run: flutter build apk --release
      
      - uses: actions/upload-artifact@v3
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk